version: "3.8"

services:
  react-app:
    container_name: frontend
    image: frontend
    build:
      context: .
      target: development
    volumes:
      - ./src:/react-app/src
    ports:
      - 3000:3000
  app:
    container_name: backend
    image: backend
    build:
      context: ./backend
    ports:
      - 8000:8000